### PR TITLE
Building with Responsive Design and Design your own Grid-based framework projects complete

### PR DESCRIPTION
**Pull request by fivan18**
# Completed projects #6 and #8 - TNW clone

This project consisted of making a clone of the [TNW](https://thenextweb.com/) page. We accomplished it by:
- [x] Building with responsive design
- [x] Designing out our own grid-based framework

### Building with Responsive Design (project #6)
- [x] Align all elements with float and flex or grid
- [x] This page should contain 3 breakpoints
- [x] The page layout does not break on smaller screens

### Design your own Grid-based framework (project #8)
- [x] Breakpoint for small screens with a width of up to 720px
- [x] Breakpoint for medium screens with a width in the range of 720px - 1024px
- [x] Breakpoint for large screens with width above 1024px

## Demo
[https://rawcdn.githack.com/fivan18/tnw-clone/06da903b0d031cdd6e3d6c6a39142d24196e288c/index.html](https://rawcdn.githack.com/fivan18/tnw-clone/06da903b0d031cdd6e3d6c6a39142d24196e288c/index.html)

## Authors
👤 **Ivan Ulises Guzman Sanchez**
- Github: [@fivan18](https://github.com/fivan18)

👤 **Tigpezeghe Rodrige K.**
- Github: [@Trodrige](https://github.com/Trodrige)

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello team! Your project is amazing and almost ready to merge, I also really love how detailed your PR is :smile: 
Please look into the following tiny details and request a re-review :handshake: 
#### Responsiveness
You've done a great job with the responsiveness, however, there are a few things that break,
please see the following screenshots below and make appropriate corrections
screenshot
screenshot
screenshot

### Summary
Please work on the few things I listed above in line with the responsiveness. After this is done, I'm sure any TSE(myself included) will be happy to approve your PR. See you at the top guys!

##### I missed something? Need help? Or you just wanna chat? Leave me a message on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin) and I will be happy to speak with you

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good job team,
##### The project looks perfect, go ahead and merge the project to master.
## project is approved💪  
Happy new year🎊

**Pull request merged**
